version: '3.3'

services:
  server:
    image: ${IMAGE_TAG:-localhost/hello-world:latest}
    build:
      context: $MONOREPO_PATH # repo root
      dockerfile: ./src/python/services/hello-world/Dockerfile
    command: poetry run python hello_world/app.py
    ports:
      - 5050:5050
  hello-world-tests:
    image: ${IMAGE_TAG:-localhost/hello-world:latest}
    build:
      context: $MONOREPO_PATH # repo root
      dockerfile: ./src/python/services/hello-world/Dockerfile
    command: poetry run pytest tests
    depends_on:
      - server
