# Базовый ci

name: check

on:
  push:
    branches:
      - '**'
    tags:
      - 'release-*'
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.10
        virtualenvs-create: false
        installer-parallel: true
    - name: build_and_test.sh
      run: cd build_scripts && ./build_and_test.sh || exit 1